export const MEMBERS_COPY = {
  ar: {
    home: 'الرئيسية',
    members: 'الأعضاء',
    breadcrumb: 'مسار التنقل',
    lede: 'تعرّف على أعضاء المجتمع وقادته.',
    leadership: 'قيادة المجتمع',
    directory: 'دليل الأعضاء',
    search: 'ابحث بالاسم',
    searchBtn: 'بحث',
    track: 'المسار',
    university: 'الجامعة',
    all: 'الكل',
    apply: 'تطبيق',
    clear: 'مسح الكل',
    count: (n: number) => `${n} عضواً`,
    more: 'عرض المزيد',
    emptyTitle: 'لم يُدرج أي عضو في الدليل بعد',
    emptyBody: 'يظهر الأعضاء هنا عندما يختارون الإدراج في الدليل.',
    noResults: 'لا أعضاء يطابقون بحثك',
    noResultsBody: 'جرّب كلمات أقل أو امسح الفلاتر.',
    clearFilters: 'مسح الفلاتر',
    ctaTitle: 'لست عضواً بعد؟ انضم إلينا',
    ctaApply: 'قدّم طلب العضوية',
    filterLabel: 'تصفية',
    removeFilter: (v: string) => `إزالة الفلتر: ${v}`,
    // profile
    about: 'نبذة',
    links: 'الروابط',
    articles: 'المقالات',
    back: 'العودة إلى دليل الأعضاء',
    editProfile: 'تعديل ملفي',
    ownNote: 'هكذا يرى الزوار ملفك.',
    newTab: '(يفتح في نافذة جديدة)',
    portfolio: 'الموقع الشخصي',
  },
  en: {
    home: 'Home',
    members: 'Members',
    breadcrumb: 'Breadcrumb',
    lede: 'Meet the community members and its leaders.',
    leadership: 'Community leadership',
    directory: 'Member directory',
    search: 'Search by name',
    searchBtn: 'Search',
    track: 'Track',
    university: 'University',
    all: 'All',
    apply: 'Apply',
    clear: 'Clear all',
    count: (n: number) => `${n} members`,
    more: 'Load more',
    emptyTitle: 'No members are listed yet',
    emptyBody: 'Members appear here when they choose to be listed in the directory.',
    noResults: 'No members match your search',
    noResultsBody: 'Try fewer words or clear the filters.',
    clearFilters: 'Clear filters',
    ctaTitle: 'Not a member yet? Join us',
    ctaApply: 'Apply for membership',
    filterLabel: 'Filter',
    removeFilter: (v: string) => `Remove filter: ${v}`,
    about: 'About',
    links: 'Links',
    articles: 'Articles',
    back: 'Back to the member directory',
    editProfile: 'Edit my profile',
    ownNote: 'This is how visitors see your profile.',
    newTab: '(opens in a new tab)',
    portfolio: 'Website',
  },
} as const;
