/** Strings of the v2 event page (PUBLIC-SCREENS-V2/02-event-page.md). */
export const EVENT_COPY = {
  ar: {
    home: 'الرئيسية',
    events: 'الفعاليات',
    breadcrumb: 'مسار التنقل',
    types: {
      workshop: 'ورشة',
      bootcamp: 'معسكر',
      hackathon: 'هاكاثون',
      meeting: 'لقاء',
      meetup: 'لقاء',
      talk: 'محاضرة',
    } as Record<string, string>,
    register: 'سجّل الآن',
    waitlist: 'انضم لقائمة الانتظار',
    apply: 'قدّم طلب العضوية',
    checkIn: 'سجّل حضورك',
    calendar: 'أضف إلى التقويم',
    share: 'مشاركة',
    copied: 'تم نسخ الرابط',
    opensOn: (d: string) => `التسجيل يفتح ${d}`,
    full: 'اكتمل العدد',
    closed: 'التسجيل مغلق',
    closesIn: (rel: string) => `يُغلق التسجيل ${rel}`,
    deadline: (d: string) => `يُغلق التسجيل ${d}`,
    seatsLeft: (n: number) => `بقي ${n} مقاعد`,
    seatsOf: (left: number, total: number) => `${left} من ${total} مقعداً متبقياً`,
    waitlistPromise: 'سنراسلك إن توفّر مقعد.',
    dateTbd: 'يُعلن الموعد قريباً',
    online: 'عبر الإنترنت',
    inPerson: 'حضوري',
    openMaps: 'افتح في الخرائط',
    newTab: '(يفتح في نافذة جديدة)',
    onlineLink: 'يصل رابط اللقاء إلى المسجّلين المقبولين قبل الموعد.',
    certEveryone: 'تُمنح شهادة حضور لمن يحضر الفعالية، وتصل بالبريد بعد الفعالية.',
    cert: (n: number) =>
      `تُمنح شهادة حضور لمن يحضر ${n}% من الجلسات أو أكثر، وتصل بالبريد بعد الفعالية.`,
    certAfter: 'تصل الشهادات بالبريد بعد اعتماد الحضور.',
    contact: 'أسئلة؟',
    onThisPage: 'أقسام الصفحة',
    sections: {
      about: 'عن الفعالية',
      agenda: 'البرنامج',
      speakers: 'المتحدثون',
      forWhom: 'لمن هذه الفعالية',
      place: 'المكان',
      bring: 'ماذا تحضر',
      faq: 'الأسئلة الشائعة',
      details: 'التفاصيل',
      related: 'فعاليات ذات صلة',
    },
    goals: 'الأهداف',
    audience: 'الفئة المستهدفة',
    day: (n: number) => `اليوم ${n}`,
    happeningNow: 'جارية الآن',
    roles: { presenter: 'مقدّم', mentor: 'مرشد', judge: 'محكّم', host: 'مضيف' },
    detailGroups: {
      responsibilities: 'المهام',
      requirements: 'المتطلبات',
      deliverables: 'المخرجات',
      benefits: 'المزايا',
    },
    allEvents: 'كل الفعاليات',
    cancelledTitle: 'أُلغيت هذه الفعالية',
    registeredTitle: 'أنت مسجّل',
    reviewTitle: 'طلبك قيد المراجعة',
    waitlistedTitle: 'أنت في قائمة الانتظار',
    sentTo: (e: string) => `أرسلنا التفاصيل إلى ${e}.`,
    cancelReg: 'إلغاء التسجيل',
    cancelConfirm: 'هل تريد إلغاء تسجيلك في هذه الفعالية؟',
    cancelYes: 'نعم، ألغِ التسجيل',
    keep: 'تراجع',
    cancelled: 'تم إلغاء تسجيلك.',
    seatsBar: 'المقاعد',
    close: 'إغلاق',
  },
  en: {
    home: 'Home',
    events: 'Events',
    breadcrumb: 'Breadcrumb',
    types: {
      workshop: 'Workshop',
      bootcamp: 'Bootcamp',
      hackathon: 'Hackathon',
      meeting: 'Meeting',
      meetup: 'Meetup',
      talk: 'Talk',
    } as Record<string, string>,
    register: 'Register now',
    waitlist: 'Join the waiting list',
    apply: 'Apply for membership',
    checkIn: 'Check in',
    calendar: 'Add to calendar',
    share: 'Share',
    copied: 'Link copied',
    opensOn: (d: string) => `Registration opens ${d}`,
    full: 'Full',
    closed: 'Registration closed',
    closesIn: (rel: string) => `Registration closes ${rel}`,
    deadline: (d: string) => `Registration closes ${d}`,
    seatsLeft: (n: number) => `${n} seats left`,
    seatsOf: (left: number, total: number) => `${left} of ${total} seats left`,
    waitlistPromise: "We'll e-mail you if a seat opens.",
    dateTbd: 'Date to be announced',
    online: 'Online',
    inPerson: 'In person',
    openMaps: 'Open in maps',
    newTab: '(opens in a new tab)',
    onlineLink: 'Accepted registrants get the meeting link before it starts.',
    certEveryone:
      'Everyone who attends gets a certificate of attendance by e-mail after the event.',
    cert: (n: number) =>
      `Attend at least ${n}% of the sessions to get a certificate of attendance by e-mail after the event.`,
    certAfter: 'Certificates are e-mailed once attendance is approved.',
    contact: 'Questions?',
    onThisPage: 'On this page',
    sections: {
      about: 'About',
      agenda: 'Agenda',
      speakers: 'Speakers',
      forWhom: 'Who it is for',
      place: 'Place',
      bring: 'What to bring',
      faq: 'FAQ',
      details: 'Details',
      related: 'Related events',
    },
    goals: 'Goals',
    audience: 'Audience',
    day: (n: number) => `Day ${n}`,
    happeningNow: 'Happening now',
    roles: { presenter: 'Presenter', mentor: 'Mentor', judge: 'Judge', host: 'Host' },
    detailGroups: {
      responsibilities: 'Responsibilities',
      requirements: 'Requirements',
      deliverables: 'Deliverables',
      benefits: 'Benefits',
    },
    allEvents: 'All events',
    cancelledTitle: 'This event was cancelled',
    registeredTitle: "You're registered",
    reviewTitle: 'Your request is under review',
    waitlistedTitle: "You're on the waiting list",
    sentTo: (e: string) => `We sent the details to ${e}.`,
    cancelReg: 'Cancel registration',
    cancelConfirm: 'Do you want to cancel your registration for this event?',
    cancelYes: 'Yes, cancel it',
    keep: 'Keep it',
    cancelled: 'Your registration was cancelled.',
    seatsBar: 'Seats',
    close: 'Close',
  },
} as const;
