"""Generates supabase/migrations/20261206000000_events.sql (Sprint 05 · EVT-006).

The migration is committed; this generator is kept so the repetitive payload-to-column handling in
`save_event` stays in one table (FIELDS) and cannot drift. Run: python scripts/gen-events-migration.py
"""
import pathlib

# (payload key, column, kind)
FIELDS = [
    ('type', 'type', 'text_required'),
    ('title_ar', 'title_ar', 'text_required'),
    ('title_en', 'title_en', 'text'),
    ('summary_ar', 'summary_ar', 'text'),
    ('summary_en', 'summary_en', 'text'),
    ('description_ar', 'description_ar', 'text'),
    ('description_en', 'description_en', 'text'),
    ('schedule_type', 'schedule_type', 'text_required'),
    ('start_date', 'start_date', 'date'),
    ('end_date', 'end_date', 'date'),
    ('start_time', 'start_time', 'time'),
    ('end_time', 'end_time', 'time'),
    ('location_mode', 'location_mode', 'text_required'),
    ('location_ar', 'location_ar', 'text'),
    ('location_en', 'location_en', 'text'),
    ('map_url', 'map_url', 'text'),
    ('seats', 'seats', 'int'),
    ('registration_start_at', 'registration_start_at', 'timestamptz'),
    ('registration_end_at', 'registration_end_at', 'timestamptz'),
    ('requires_approval', 'requires_approval', 'bool'),
    ('waitlist_enabled', 'waitlist_enabled', 'bool'),
    ('audience', 'audience', 'text_required'),
    ('goals', 'goals', 'jsonb'),
    ('faq', 'faq', 'jsonb'),
    ('details', 'details', 'jsonb'),
    ('display_config', 'display_config', 'jsonb'),
    ('cover_image_path', 'cover_image_path', 'text'),
    ('awards_ar', 'awards_ar', 'text'),
    ('awards_en', 'awards_en', 'text'),
    ('certificate_available', 'certificate_available', 'bool'),
    ('contact_email', 'contact_email', 'text'),
    ('contact_phone', 'contact_phone', 'text'),
]

PRIVATE = ['meeting_url', 'meeting_notes', 'group_link', 'organizer_notes']


def assign(key, col, kind):
    src = f"p->>'{key}'"
    if kind == 'text_required':
        expr = src
    elif kind == 'text':
        expr = f"nullif(btrim({src}), '')"
    elif kind == 'date':
        expr = f"nullif({src}, '')::date"
    elif kind == 'time':
        expr = f"nullif({src}, '')::time"
    elif kind == 'timestamptz':
        expr = f"nullif({src}, '')::timestamptz"
    elif kind == 'int':
        expr = f"nullif({src}, '')::integer"
    elif kind == 'bool':
        expr = f"({src})::boolean"
    elif kind == 'jsonb':
        expr = f"p->'{key}'"
    else:
        raise ValueError(kind)
    return f"  if p ? '{key}' then v.{col} := {expr}; end if;"


field_lines = '\n'.join(assign(*f) for f in FIELDS)
private_lines = '\n'.join(
    f"  if p ? '{k}' then d_{k} := nullif(btrim(p->>'{k}'), ''); has_private := true; end if;" for k in PRIVATE
)
private_cols = ', '.join(PRIVATE)
private_vars = '\n'.join(f"  d_{k} text;" for k in PRIVATE)
private_upsert_vals = ', '.join(f"d_{k}" for k in PRIVATE)
private_upsert_set = ', '.join(f"{k} = case when p ? '{k}' then excluded.{k} else public.event_private_details.{k} end" for k in PRIVATE)

SQL = f"""-- Sprint 05 · EVT-006, EVT-011 — events, private details, dates, presenters, phase view, lifecycle functions.
-- GENERATED by scripts/gen-events-migration.py (field handling) — edit the generator, not the repeated blocks.
-- Authoritative design: docs/05-database/entities/events.md, docs/03-business-domain/event-lifecycle.md,
-- docs/11-modules/events/README.md, ADR-012 (KFUCS-aligned model).

-- ------------------------------------------------------------------------------------------ helpers
create or replace function private.slugify(p_text text)
returns text
language sql
immutable
set search_path = ''
as $$
  select btrim(regexp_replace(lower(coalesce(p_text, '')), '[^a-z0-9]+', '-', 'g'), '-')
$$;

-- ------------------------------------------------------------------------------------------ events
create table public.events (
  id                       uuid primary key default gen_random_uuid(),
  legacy_id                integer unique,
  slug                     text not null unique check (slug ~ '^[a-z0-9-]+$' and char_length(slug) between 3 and 120),
  committee_id             uuid not null references public.committees (id) on delete restrict,
  type                     text not null check (type in ('workshop','bootcamp','hackathon','meeting','meetup','talk')),
  status                   text not null default 'draft'
                             check (status in ('draft','pending_review','changes_requested','published','cancelled','completed','archived')),
  title_ar                 text not null check (char_length(title_ar) between 3 and 200),
  title_en                 text check (char_length(title_en) <= 200),
  summary_ar               text check (char_length(summary_ar) <= 500),
  summary_en               text check (char_length(summary_en) <= 500),
  description_ar           text check (char_length(description_ar) <= 5000),
  description_en           text check (char_length(description_en) <= 5000),
  schedule_type            text not null default 'single_day'
                             check (schedule_type in ('single_day','consecutive_range','specific_dates')),
  start_date               date,
  end_date                 date,
  start_time               time,
  end_time                 time,
  location_mode            text not null default 'in_person' check (location_mode in ('in_person','online','hybrid')),
  location_ar              text check (char_length(location_ar) <= 500),
  location_en              text check (char_length(location_en) <= 500),
  map_url                  text check (map_url is null or map_url ~ '^https://'),
  seats                    integer check (seats is null or seats > 0),
  registration_start_at    timestamptz,
  registration_end_at      timestamptz,
  requires_approval        boolean not null default true,
  waitlist_enabled         boolean not null default false,
  audience                 text not null default 'public' check (audience in ('public','members_only')),
  goals                    jsonb not null default '{{"ar":[],"en":[]}}'::jsonb
                             check (jsonb_typeof(goals) = 'object'
                                    and jsonb_typeof(goals -> 'ar') = 'array' and jsonb_typeof(goals -> 'en') = 'array'
                                    and jsonb_array_length(goals -> 'ar') <= 15 and jsonb_array_length(goals -> 'en') <= 15),
  faq                      jsonb not null default '[]'::jsonb
                             check (jsonb_typeof(faq) = 'array' and jsonb_array_length(faq) <= 15),
  details                  jsonb not null default '{{}}'::jsonb check (jsonb_typeof(details) = 'object'),
  display_config           jsonb not null default
                             '{{"show_presenters":false,"show_goals":true,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}}'::jsonb
                             check (jsonb_typeof(display_config) = 'object'),
  cover_image_path         text,
  awards_ar                text,
  awards_en                text,
  certificate_available    boolean not null default false,
  contact_email            text,
  contact_phone            text,
  submission_note          text,
  submitted_by             uuid references public.profiles (id) on delete set null,
  submitted_at             timestamptz,
  reviewed_by              uuid references public.profiles (id) on delete set null,
  reviewed_at              timestamptz,
  review_note              text,
  published_at             timestamptz,
  cancelled_at             timestamptz,
  cancel_reason            text,
  attendance_finalized_at  timestamptz,
  attendance_finalized_by  uuid references public.profiles (id) on delete set null,
  completed_at             timestamptz,
  archived_at              timestamptz,
  created_by               uuid references public.profiles (id) on delete set null,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  constraint events_date_order check (start_date is null or end_date is null or end_date >= start_date),
  constraint events_same_day_time_order check (
    start_time is null or end_time is null
    or not (start_date is not null and (end_date is null or end_date = start_date))
    or end_time > start_time
  ),
  constraint events_cancel_reason check (status <> 'cancelled' or cancel_reason is not null)
);
comment on table public.events is 'Events (KFUCS-aligned). Written only through save_event/transition_event/delete_event_draft.';
create index events_status_start_idx on public.events (status, start_date desc);
create index events_published_start_idx on public.events (start_date) where status = 'published';
create index events_committee_status_idx on public.events (committee_id, status);
create trigger events_touch_updated_at before update on public.events
  for each row execute function private.touch_updated_at();

-- EV-9: the slug is locked after the first publish.
create or replace function private.events_slug_lock()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.published_at is not null and new.slug is distinct from old.slug then
    raise exception 'SLUG_LOCKED' using errcode = 'P0001';
  end if;
  return new;
end;
$$;
create trigger events_slug_lock before update on public.events
  for each row execute function private.events_slug_lock();

-- EV-5: status only changes inside transition_event (which sets the flag for its own transaction).
create or replace function private.events_status_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status is distinct from old.status and coalesce(current_setting('app.event_transition', true), '') <> 'on' then
    raise exception 'INVALID_TRANSITION' using errcode = 'P0001';
  end if;
  return new;
end;
$$;
create trigger events_status_guard before update on public.events
  for each row execute function private.events_status_guard();

-- ------------------------------------------------------------------------------------------ private details
create table public.event_private_details (
  event_id        uuid primary key references public.events (id) on delete cascade,
  meeting_url     text check (meeting_url is null or meeting_url ~ '^https://'),
  meeting_notes   text check (char_length(meeting_notes) <= 1000),
  group_link      text check (group_link is null or group_link ~ '^https://'),
  organizer_notes text,
  updated_at      timestamptz not null default now()
);
comment on table public.event_private_details is 'Links only organizers and accepted registrants may read (EV-7).';
create trigger event_private_details_touch before update on public.event_private_details
  for each row execute function private.touch_updated_at();

-- ------------------------------------------------------------------------------------------ dates
create table public.event_dates (
  id         uuid primary key default gen_random_uuid(),
  event_id   uuid not null references public.events (id) on delete cascade,
  event_date date not null,
  starts_at  time,
  ends_at    time,
  unique (event_id, event_date)
);
create index event_dates_event_idx on public.event_dates (event_id, event_date);

-- Single day and consecutive range regenerate their rows; specific dates are written by save_event.
create or replace function private.sync_event_dates()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.schedule_type in ('single_day', 'consecutive_range') then
    delete from public.event_dates where event_id = new.id;
    if new.start_date is not null then
      insert into public.event_dates (event_id, event_date)
      select new.id, d::date
      from generate_series(new.start_date::timestamp,
                           coalesce(case when new.schedule_type = 'single_day' then new.start_date else new.end_date end, new.start_date)::timestamp,
                           interval '1 day') as d;
    end if;
  end if;
  return new;
end;
$$;
create trigger events_sync_dates after insert or update of schedule_type, start_date, end_date on public.events
  for each row execute function private.sync_event_dates();

-- ------------------------------------------------------------------------------------------ presenters
create table public.event_presenters (
  id               uuid primary key default gen_random_uuid(),
  event_id         uuid not null references public.events (id) on delete cascade,
  profile_id       uuid references public.profiles (id) on delete set null,
  guest_name_ar    text,
  guest_name_en    text,
  guest_title_ar   text,
  guest_title_en   text,
  guest_photo_path text,
  guest_link       text check (guest_link is null or guest_link ~ '^https://'),
  role             text not null default 'presenter' check (role in ('presenter','mentor','judge','host')),
  sort_order       smallint not null default 0,
  constraint event_presenters_identity check (profile_id is not null or guest_name_ar is not null)
);
create index event_presenters_event_idx on public.event_presenters (event_id, sort_order);

-- ------------------------------------------------------------------------------------------ RLS helpers + policies
create or replace function private.event_committee(p_event uuid)
returns uuid
language sql
stable
security definer
set search_path = ''
as $$ select committee_id from public.events where id = p_event $$;
revoke all on function private.event_committee(uuid) from public;
grant execute on function private.event_committee(uuid) to anon, authenticated;

alter table public.events enable row level security;
alter table public.event_private_details enable row level security;
alter table public.event_dates enable row level security;
alter table public.event_presenters enable row level security;

revoke all on table public.events, public.event_private_details, public.event_dates, public.event_presenters
  from anon, authenticated;
grant select on public.events, public.event_dates, public.event_presenters to anon, authenticated;
grant select on public.event_private_details to authenticated;

create policy events_select_public on public.events
  for select to anon, authenticated
  using (status in ('published','cancelled','completed','archived'));
create policy events_select_scope on public.events
  for select to authenticated
  using (private.has_permission('events.view_drafts', committee_id));

create policy event_dates_select on public.event_dates
  for select to anon, authenticated
  using (exists (select 1 from public.events e where e.id = event_id));
create policy event_presenters_select on public.event_presenters
  for select to anon, authenticated
  using (exists (select 1 from public.events e where e.id = event_id));
create policy event_private_select_organizers on public.event_private_details
  for select to authenticated
  using (private.has_permission('events.edit', private.event_committee(event_id)));

-- ------------------------------------------------------------------------------------------ phase (derived, never stored)
create or replace function private.event_phase(
  p_status text, p_start_date date, p_last_date date, p_start_time time, p_end_time time,
  p_reg_start timestamptz, p_reg_end timestamptz, p_seats integer, p_accepted integer, p_auto_close boolean,
  p_now timestamptz default now()
) returns text
language sql
stable
set search_path = ''
as $$
  select case
    when p_status = 'cancelled' then 'cancelled'
    when p_status in ('completed', 'archived') then 'ended'
    when p_status <> 'published' then null
    else (
      with t as (
        select
          (p_now at time zone 'Asia/Riyadh') as n,
          case when p_start_date is null then null else p_start_date + coalesce(p_start_time, time '00:00') end as first_start,
          case when p_last_date is null then null else p_last_date + coalesce(p_end_time, time '23:59:59') end as last_end,
          (p_reg_start at time zone 'Asia/Riyadh') as rs,
          coalesce(p_reg_end at time zone 'Asia/Riyadh', case when p_start_date is null then null else p_start_date + time '23:59:59' end) as re
      )
      select case
        when last_end is not null and n >= last_end then 'ended'
        when first_start is null then 'announced'
        when rs is not null and n < rs then 'announced'
        when re > n and not (coalesce(p_auto_close, true) and p_seats is not null and p_accepted >= p_seats) then 'registration_open'
        when n < first_start then 'registration_closed'
        else 'in_progress'
      end from t
    )
  end
$$;
grant execute on function private.event_phase(text, date, date, time, time, timestamptz, timestamptz, integer, integer, boolean, timestamptz) to anon, authenticated;

-- Public read model: only public statuses, public columns, derived phase. Runs with the owner's rights on purpose.
create view public.public_events as
select
  e.id, e.legacy_id, e.slug, e.committee_id,
  c.slug as committee_slug, c.name_ar as committee_name_ar, c.name_en as committee_name_en,
  e.type, e.status,
  e.title_ar, e.title_en, e.summary_ar, e.summary_en, e.description_ar, e.description_en,
  e.schedule_type, e.start_date, e.end_date, e.start_time, e.end_time,
  coalesce((select max(d.event_date) from public.event_dates d where d.event_id = e.id), e.end_date, e.start_date) as last_date,
  e.location_mode, e.location_ar, e.location_en, e.map_url,
  e.seats, e.registration_start_at, e.registration_end_at, e.requires_approval, e.waitlist_enabled, e.audience,
  e.goals, e.faq, e.details, e.display_config,
  e.cover_image_path, e.awards_ar, e.awards_en, e.certificate_available, e.contact_email, e.contact_phone,
  e.published_at, e.cancelled_at, e.cancel_reason,
  0::integer as accepted_count,
  case when e.seats is null then null else e.seats end as seats_left,
  private.event_phase(
    e.status, e.start_date,
    coalesce((select max(d.event_date) from public.event_dates d where d.event_id = e.id), e.end_date, e.start_date),
    e.start_time, e.end_time, e.registration_start_at, e.registration_end_at, e.seats, 0,
    (e.display_config ->> 'auto_close_registration')::boolean
  ) as phase
from public.events e
join public.committees c on c.id = e.committee_id
where e.status in ('published', 'cancelled', 'completed', 'archived');
comment on view public.public_events is 'Public events with the derived timing phase (EV-6).';
revoke all on public.public_events from anon, authenticated;
grant select on public.public_events to anon, authenticated;

-- Dashboard tab counts, under the caller's RLS (a head only counts their committee).
create view public.event_status_counts with (security_invoker = true) as
select status, count(*)::integer as total from public.events group by status;
revoke all on public.event_status_counts from anon;
grant select on public.event_status_counts to authenticated;

-- ------------------------------------------------------------------------------------------ guards
-- Returns the first missing publish requirement (or null). Used by submit (INCOMPLETE) and approve (PUBLISH_GUARD).
create or replace function private.event_missing_requirement(p_event uuid)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  e public.events;
  d public.event_private_details;
begin
  select * into e from public.events where id = p_event;
  select * into d from public.event_private_details where event_id = p_event;
  if e.start_date is null then return 'start_date'; end if;
  if e.schedule_type = 'consecutive_range' and e.end_date is null then return 'end_date'; end if;
  if e.schedule_type = 'specific_dates' and not exists (select 1 from public.event_dates where event_id = p_event) then
    return 'dates';
  end if;
  if e.location_mode in ('in_person', 'hybrid') and coalesce(btrim(e.location_ar), '') = '' then return 'location'; end if;
  if coalesce(d.group_link, '') = '' then return 'group_link'; end if;
  if jsonb_array_length(coalesce(e.goals -> 'ar', '[]'::jsonb)) < 1 then return 'goals'; end if;
  return null;
end;
$$;
revoke all on function private.event_missing_requirement(uuid) from public, anon, authenticated;

-- ------------------------------------------------------------------------------------------ save_event
create or replace function public.save_event(
  p_event_id uuid,
  p jsonb,
  p_expected_updated_at timestamptz default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v public.events;
  old public.events;
  is_new boolean := p_event_id is null;
  caller uuid := (select auth.uid());
  has_private boolean := false;
{private_vars}
  slug_in text;
  base text;
  n integer := 0;
  significant boolean := false;
  presenter jsonb;
  idx integer := 0;
  committee_status text;
begin
  if caller is null then raise exception 'UNAUTHENTICATED' using errcode = 'P0001'; end if;

  if is_new then
    v.id := gen_random_uuid();
    v.status := 'draft';
    v.created_by := caller;
    v.created_at := now();
    v.updated_at := now();
    v.type := coalesce(p ->> 'type', 'workshop');
    v.schedule_type := 'single_day';
    v.location_mode := 'in_person';
    v.audience := 'public';
    v.requires_approval := true;
    v.waitlist_enabled := false;
    v.certificate_available := false;
    v.goals := '{{"ar":[],"en":[]}}'::jsonb;
    v.faq := '[]'::jsonb;
    v.details := '{{}}'::jsonb;
    v.display_config := '{{"show_presenters":false,"show_goals":true,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}}'::jsonb;
    v.committee_id := nullif(p ->> 'committee_id', '')::uuid;
    if v.committee_id is null then raise exception 'SCOPE_REQUIRED' using errcode = 'P0001'; end if;
    if not private.has_permission('events.create', v.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
  else
    select * into old from public.events where id = p_event_id for update;
    if not found then raise exception 'NOT_FOUND' using errcode = 'P0001'; end if;
    -- A user who cannot even see the event gets NOT_FOUND (no existence leak).
    if not (private.has_permission('events.view_drafts', old.committee_id) or old.status in ('published','cancelled','completed','archived')) then
      raise exception 'NOT_FOUND' using errcode = 'P0001';
    end if;
    if not private.has_permission('events.edit', old.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
    if old.status in ('pending_review', 'cancelled', 'completed', 'archived') then
      raise exception 'NOT_EDITABLE' using errcode = 'P0001';
    end if;
    -- Published events: the head and the leader (events.cancel marks them) may edit.
    if old.status = 'published' and not private.has_permission('events.cancel', old.committee_id) then
      raise exception 'FORBIDDEN' using errcode = 'P0001';
    end if;
    if p_expected_updated_at is not null and old.updated_at <> p_expected_updated_at then
      raise exception 'STALE_DATA' using errcode = 'P0001';
    end if;
    v := old;
    if p ? 'committee_id' and nullif(p ->> 'committee_id', '')::uuid is distinct from old.committee_id then
      v.committee_id := nullif(p ->> 'committee_id', '')::uuid;
      if not private.has_permission('events.create', v.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
    end if;
  end if;

  select status into committee_status from public.committees where id = v.committee_id;
  if committee_status is null then raise exception 'NOT_FOUND' using errcode = 'P0001'; end if;
  if (is_new or v.committee_id is distinct from old.committee_id) and committee_status <> 'active' then
    raise exception 'COMMITTEE_INACTIVE' using errcode = 'P0001';
  end if;

{field_lines}

  -- slug: provided (checked) or generated once for a new event
  slug_in := nullif(btrim(p ->> 'slug'), '');
  if slug_in is not null then
    if old.published_at is not null and slug_in <> old.slug then raise exception 'SLUG_LOCKED' using errcode = 'P0001'; end if;
    v.slug := slug_in;
    if exists (select 1 from public.events where slug = v.slug and id <> v.id) then raise exception 'SLUG_TAKEN' using errcode = 'P0001'; end if;
  elsif is_new then
    base := private.slugify(coalesce(v.title_en, ''));
    if char_length(base) < 3 then base := 'event'; end if;
    v.slug := base;
    while exists (select 1 from public.events where slug = v.slug) loop
      n := n + 1;
      v.slug := base || '-' || substr(md5(random()::text || n::text), 1, 5);
    end loop;
  end if;

  -- private details
  {private_lines.strip()}

  if is_new then
    insert into public.events select v.*;
  else
    -- significant change on a published event (dates, mode, place) → caller notifies registrants (Sprint 06)
    significant := old.status = 'published' and (
      v.start_date is distinct from old.start_date or v.end_date is distinct from old.end_date
      or v.start_time is distinct from old.start_time or v.end_time is distinct from old.end_time
      or v.location_mode is distinct from old.location_mode or v.location_ar is distinct from old.location_ar
      or v.schedule_type is distinct from old.schedule_type
    );
    update public.events set
      committee_id = v.committee_id, slug = v.slug, type = v.type, title_ar = v.title_ar, title_en = v.title_en,
      summary_ar = v.summary_ar, summary_en = v.summary_en, description_ar = v.description_ar, description_en = v.description_en,
      schedule_type = v.schedule_type, start_date = v.start_date, end_date = v.end_date, start_time = v.start_time, end_time = v.end_time,
      location_mode = v.location_mode, location_ar = v.location_ar, location_en = v.location_en, map_url = v.map_url,
      seats = v.seats, registration_start_at = v.registration_start_at, registration_end_at = v.registration_end_at,
      requires_approval = v.requires_approval, waitlist_enabled = v.waitlist_enabled, audience = v.audience,
      goals = v.goals, faq = v.faq, details = v.details, display_config = v.display_config,
      cover_image_path = v.cover_image_path, awards_ar = v.awards_ar, awards_en = v.awards_en,
      certificate_available = v.certificate_available, contact_email = v.contact_email, contact_phone = v.contact_phone
    where id = v.id;
  end if;

  if has_private or is_new then
    insert into public.event_private_details (event_id, {private_cols})
    values (v.id, {private_upsert_vals})
    on conflict (event_id) do update set {private_upsert_set};
  end if;

  -- specific dates: replace the rows (single day / range are handled by the trigger)
  if v.schedule_type = 'specific_dates' and p ? 'dates' then
    delete from public.event_dates where event_id = v.id;
    insert into public.event_dates (event_id, event_date)
    select v.id, d::date from (select distinct jsonb_array_elements_text(p -> 'dates') as d) x;
    update public.events set start_date = (select min(event_date) from public.event_dates where event_id = v.id),
                             end_date = (select max(event_date) from public.event_dates where event_id = v.id)
     where id = v.id;
  end if;

  -- presenters: replace the set (≤ 10)
  if p ? 'presenters' then
    if jsonb_array_length(p -> 'presenters') > 10 then raise exception 'VALIDATION_FAILED' using errcode = 'P0001'; end if;
    delete from public.event_presenters where event_id = v.id;
    for presenter in select * from jsonb_array_elements(p -> 'presenters') loop
      insert into public.event_presenters (event_id, profile_id, guest_name_ar, guest_name_en, guest_title_ar, guest_title_en, guest_photo_path, guest_link, role, sort_order)
      values (
        v.id, nullif(presenter ->> 'profile_id', '')::uuid,
        nullif(btrim(presenter ->> 'guest_name_ar'), ''), nullif(btrim(presenter ->> 'guest_name_en'), ''),
        nullif(btrim(presenter ->> 'guest_title_ar'), ''), nullif(btrim(presenter ->> 'guest_title_en'), ''),
        nullif(presenter ->> 'guest_photo_path', ''), nullif(presenter ->> 'guest_link', ''),
        coalesce(nullif(presenter ->> 'role', ''), 'presenter'), idx
      );
      idx := idx + 1;
    end loop;
  end if;

  perform private.write_audit(case when is_new then 'event.created' else 'event.updated' end, 'event', v.id::text, v.committee_id,
    jsonb_build_object('slug', v.slug, 'status', coalesce(old.status, 'draft'), 'significant_change', significant));

  return (select jsonb_build_object('id', e.id, 'slug', e.slug, 'status', e.status, 'updated_at', e.updated_at, 'significant_change', significant)
            from public.events e where e.id = v.id);
end;
$$;

-- ------------------------------------------------------------------------------------------ transition_event
create or replace function public.transition_event(p_id uuid, p_action text, p_note text default null)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  e public.events;
  caller uuid := (select auth.uid());
  to_status text;
  audit_action text;
  missing text;
  note text := nullif(btrim(coalesce(p_note, '')), '');
  event_last_date date;
begin
  if caller is null then raise exception 'UNAUTHENTICATED' using errcode = 'P0001'; end if;
  select * into e from public.events where id = p_id for update;
  if not found or not (private.has_permission('events.view_drafts', e.committee_id) or e.status in ('published','cancelled','completed','archived')) then
    raise exception 'NOT_FOUND' using errcode = 'P0001';
  end if;

  case p_action
    when 'submit' then
      if not private.has_permission('events.submit', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
      if e.status not in ('draft', 'changes_requested') then raise exception 'INVALID_TRANSITION' using errcode = 'P0001'; end if;
      missing := private.event_missing_requirement(e.id);
      if missing is not null then raise exception 'INCOMPLETE:%', missing using errcode = 'P0001'; end if;
      to_status := 'pending_review'; audit_action := 'event.submitted';
    when 'withdraw' then
      if not private.has_permission('events.submit', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
      if e.status <> 'pending_review' then raise exception 'INVALID_TRANSITION' using errcode = 'P0001'; end if;
      to_status := 'draft'; audit_action := 'event.withdrawn';
    when 'approve' then
      if not private.has_permission('events.approve', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
      if e.status not in ('pending_review', 'draft') then raise exception 'INVALID_TRANSITION' using errcode = 'P0001'; end if;
      missing := private.event_missing_requirement(e.id);
      if missing is not null then raise exception 'PUBLISH_GUARD:%', missing using errcode = 'P0001'; end if;
      to_status := 'published'; audit_action := 'event.approved';
    when 'request_changes' then
      if not private.has_permission('events.approve', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
      if e.status <> 'pending_review' then raise exception 'INVALID_TRANSITION' using errcode = 'P0001'; end if;
      if note is null or char_length(note) < 10 then raise exception 'NOTE_TOO_SHORT' using errcode = 'P0001'; end if;
      to_status := 'changes_requested'; audit_action := 'event.changes_requested';
    when 'cancel' then
      if not private.has_permission('events.cancel', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
      if e.status <> 'published' then raise exception 'INVALID_TRANSITION' using errcode = 'P0001'; end if;
      if note is null then raise exception 'REASON_REQUIRED' using errcode = 'P0001'; end if;
      to_status := 'cancelled'; audit_action := 'event.cancelled';
    when 'complete' then
      if not private.has_permission('events.complete', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
      if e.status <> 'published' then raise exception 'INVALID_TRANSITION' using errcode = 'P0001'; end if;
      select coalesce(max(event_date), e.end_date, e.start_date) into event_last_date from public.event_dates where event_id = e.id;
      if event_last_date is null or event_last_date >= (now() at time zone 'Asia/Riyadh')::date then
        raise exception 'EVENT_NOT_ENDED' using errcode = 'P0001';
      end if;
      -- Sprint 10 adds: ATTENDANCE_NOT_FINALIZED when sessions exist and are not all finalized.
      to_status := 'completed'; audit_action := 'event.completed';
    when 'archive' then
      if not private.has_permission('events.complete', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
      if e.status not in ('completed', 'cancelled') then raise exception 'INVALID_TRANSITION' using errcode = 'P0001'; end if;
      to_status := 'archived'; audit_action := 'event.archived';
    else
      raise exception 'INVALID_TRANSITION' using errcode = 'P0001';
  end case;

  perform set_config('app.event_transition', 'on', true);
  update public.events set
    status = to_status,
    submitted_by = case when p_action = 'submit' then caller else submitted_by end,
    submitted_at = case when p_action = 'submit' then now() else submitted_at end,
    submission_note = case when p_action = 'submit' then note else submission_note end,
    reviewed_by = case when p_action in ('approve', 'request_changes') then caller else reviewed_by end,
    reviewed_at = case when p_action in ('approve', 'request_changes') then now() else reviewed_at end,
    review_note = case when p_action in ('approve', 'request_changes') then note else review_note end,
    published_at = case when p_action = 'approve' then coalesce(published_at, now()) else published_at end,
    cancelled_at = case when p_action = 'cancel' then now() else cancelled_at end,
    cancel_reason = case when p_action = 'cancel' then note else cancel_reason end,
    completed_at = case when p_action = 'complete' then now() else completed_at end,
    archived_at = case when p_action = 'archive' then now() else archived_at end
  where id = e.id;
  perform set_config('app.event_transition', 'off', true);

  perform private.write_audit(audit_action, 'event', e.id::text, e.committee_id,
    jsonb_build_object('from', e.status, 'to', to_status, 'note', note, 'direct', (p_action = 'approve' and e.status = 'draft')));
  return to_status;
end;
$$;

-- ------------------------------------------------------------------------------------------ delete + history
create or replace function public.delete_event_draft(p_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  e public.events;
begin
  if (select auth.uid()) is null then raise exception 'UNAUTHENTICATED' using errcode = 'P0001'; end if;
  select * into e from public.events where id = p_id for update;
  if not found or not private.has_permission('events.view_drafts', e.committee_id) then raise exception 'NOT_FOUND' using errcode = 'P0001'; end if;
  if not private.has_permission('events.delete', e.committee_id) then raise exception 'FORBIDDEN' using errcode = 'P0001'; end if;
  if e.status not in ('draft', 'changes_requested') or e.published_at is not null then
    raise exception 'NOT_DELETABLE' using errcode = 'P0001';
  end if;
  delete from public.events where id = e.id;
  perform private.write_audit('event.deleted', 'event', e.id::text, e.committee_id, jsonb_build_object('slug', e.slug));
end;
$$;

-- Event history for people who can see the event (no audit.view needed).
create or replace function public.event_history(p_id uuid)
returns table (occurred_at timestamptz, action text, actor_name text, summary jsonb)
language sql
stable
security definer
set search_path = ''
as $$
  select a.occurred_at, a.action, p.full_name_ar, a.summary
  from public.audit_logs a
  left join public.profiles p on p.id = a.actor_id
  where a.entity_type = 'event' and a.entity_id = p_id::text
    and private.has_permission('events.view_drafts', private.event_committee(p_id))
  order by a.occurred_at desc, a.id desc
$$;

revoke all on function public.save_event(uuid, jsonb, timestamptz) from public, anon;
revoke all on function public.transition_event(uuid, text, text) from public, anon;
revoke all on function public.delete_event_draft(uuid) from public, anon;
revoke all on function public.event_history(uuid) from public, anon;
grant execute on function public.save_event(uuid, jsonb, timestamptz) to authenticated;
grant execute on function public.transition_event(uuid, text, text) to authenticated;
grant execute on function public.delete_event_draft(uuid) to authenticated;
grant execute on function public.event_history(uuid) to authenticated;

-- ------------------------------------------------------------------------------------------ storage (covers, guest photos)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('public-media', 'public-media', true, 2097152, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy public_media_read on storage.objects
  for select to anon, authenticated using (bucket_id = 'public-media');
create policy public_media_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'public-media' and private.has_permission_any_scope('events.edit'));
create policy public_media_update on storage.objects
  for update to authenticated
  using (bucket_id = 'public-media' and private.has_permission_any_scope('events.edit'))
  with check (bucket_id = 'public-media' and private.has_permission_any_scope('events.edit'));
create policy public_media_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'public-media' and private.has_permission_any_scope('events.edit'));
"""

out = pathlib.Path(__file__).resolve().parent.parent / 'supabase' / 'migrations' / '20261206000000_events.sql'
out.write_text(SQL, encoding='utf-8')
print('wrote', out, len(SQL.splitlines()), 'lines')
