-- Sprint 06 · EVT-005 — the six hardcoded events become rows (idempotent; legacy_id is the key).
-- GENERATED by scripts/gen-legacy-events.mjs from the old pages. Registrations are mapped to these rows by legacy_id.
-- Cover images are the existing static assets (paths starting with "/"); new covers live in the public-media bucket.

insert into public.events (
    legacy_id, slug, committee_id, type, status, title_ar, title_en, schedule_type, start_date, end_date,
    location_mode, location_ar, location_en, goals, faq, details, display_config, cover_image_path,
    awards_ar, awards_en, certificate_available, contact_email, published_at
  ) values (
    1, 'github-basics-meetup', (select id from public.committees where slug = 'tech-development'), 'meetup', 'published',
    'لقاء تقني: بيئات العمل التقنية وأساسيات Github', 'Technical Meetup: Tech Work Environments and GitHub Basics', 'single_day', null, null,
    'online', 'أونلاين', 'Online', '{"ar":[],"en":[]}'::jsonb, '[{"q_ar":"","q_en":"","a_ar":"لا توجد شهادة حضور لهذه الفعالية.","a_en":"There is no attendance certificate for this event."},{"q_ar":"","q_en":"","a_ar":"في حال القبول، سيتم إرسال رسالة القبول عبر البريد الإلكتروني.","a_en":"If accepted, an approval email will be sent to your email."}]'::jsonb, '{"target_audience":{"ar":["طلاب، خريجون، موظفون"],"en":["Students, graduates, employees"]},"requirements":{"ar":["لا يوجد."],"en":["None."]},"responsibilities":{"ar":["الحضور والالتزام بوقت اللقاء.","المشاركة الفعالة أثناء النقاش.","الاستفادة من المحتوى وطرح الأسئلة عند الحاجة."],"en":["Attend and respect the meeting time.","Participate actively during the discussion.","Use the content and ask questions when needed."]},"deliverables":{"ar":["التعرف على أبرز الفروقات التقنية بين بيئات العمل في الشركات والبنوك.","التعرف على أساسيات GitHub وكيفية إنشاء حساب واستخدامه بشكل أولي."],"en":["Understand the main technical differences between work environments in companies and banks.","Learn the basics of GitHub and how to create an account and use it initially."]},"benefits":{"ar":["لا يوجد."],"en":["None."]}}'::jsonb,
    '{"show_presenters":false,"show_goals":false,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}'::jsonb,
    '/assets/event-card.png', 'لا توجد شهادة حضور', 'No attendance certificate', false, 'sdcommunity.sa@gmail.com', '2026-01-01T00:00:00+03:00'
  ) on conflict (legacy_id) do nothing;

insert into public.events (
    legacy_id, slug, committee_id, type, status, title_ar, title_en, schedule_type, start_date, end_date,
    location_mode, location_ar, location_en, goals, faq, details, display_config, cover_image_path,
    awards_ar, awards_en, certificate_available, contact_email, published_at
  ) values (
    2, 'google-ai-studio-workshop', (select id from public.committees where slug = 'tech-development'), 'workshop', 'published',
    'ورشة Google AI Studio', 'Google AI Studio Workshop', 'single_day', '2026-08-05', null,
    'online', 'أونلاين', 'Online', '{"ar":[],"en":[]}'::jsonb, '[{"q_ar":"","q_en":"","a_ar":"تتوفر شهادة حضور بعد حضور الورشة.","a_en":"An attendance certificate is available after attending the workshop."},{"q_ar":"","q_en":"","a_ar":"في حال القبول، سيتم إرسال رسالة القبول عبر البريد الإلكتروني.","a_en":"If accepted, an approval email will be sent to your email."}]'::jsonb, '{"target_audience":{"ar":["طلاب، خريجون، موظفون"],"en":["Students, graduates, employees"]},"requirements":{"ar":["لا يوجد."],"en":["None."]},"responsibilities":{"ar":["الحضور والالتزام بوقت الورشة.","المشاركة الفعالة أثناء التطبيق العملي.","متابعة الشرح وتجربة الأدوات المقدمة خلال الورشة."],"en":["Attend and respect the workshop time.","Participate actively in hands-on practice.","Follow the explanation and experiment with the tools presented."]},"deliverables":{"ar":["التعرف على Google AI Studio وأهم استخداماته.","اكتساب أساسيات التعامل مع أدوات الذكاء الاصطناعي وتطبيقها بشكل مبسط."],"en":["Learn about Google AI Studio and its main use cases.","Gain the basics of working with AI tools and applying them simply."]},"benefits":{"ar":["لا يوجد."],"en":["None."]}}'::jsonb,
    '{"show_presenters":false,"show_goals":false,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}'::jsonb,
    '/assets/Picture1.png', 'شهادة حضور', 'Attendance certificate', true, 'sdcommunity.sa@gmail.com', '2026-08-05T00:00:00+03:00'
  ) on conflict (legacy_id) do nothing;

insert into public.events (
    legacy_id, slug, committee_id, type, status, title_ar, title_en, schedule_type, start_date, end_date,
    location_mode, location_ar, location_en, goals, faq, details, display_config, cover_image_path,
    awards_ar, awards_en, certificate_available, contact_email, published_at
  ) values (
    3, 'excel-power-bi-workshop', (select id from public.committees where slug = 'tech-development'), 'workshop', 'published',
    'ورشة تحليل البيانات باستخدام Excel & Power BI', 'Data Analysis Workshop using Excel & Power BI', 'single_day', '2025-09-20', null,
    'online', 'أونلاين', 'Online', '{"ar":[],"en":[]}'::jsonb, '[{"q_ar":"","q_en":"","a_ar":"تتوفر شهادة حضور بعد حضور الورشة.","a_en":"An attendance certificate is available after attending the workshop."},{"q_ar":"","q_en":"","a_ar":"في حال القبول، سيتم إرسال رسالة القبول عبر البريد الإلكتروني.","a_en":"If accepted, an approval email will be sent to your email."}]'::jsonb, '{"target_audience":{"ar":["طلاب، خريجون، موظفون"],"en":["Students, graduates, employees"]},"requirements":{"ar":["لا يوجد."],"en":["None."]},"responsibilities":{"ar":["الحضور والالتزام بوقت الورشة.","المشاركة الفعالة أثناء التطبيق العملي.","متابعة خطوات تحليل البيانات وتجربة الأدوات المقدمة."],"en":["Attend and respect the workshop time.","Participate actively in hands-on activities.","Follow the data analysis steps and try the tools provided."]},"deliverables":{"ar":["التعرف على أساسيات تحليل البيانات باستخدام Excel وPower BI.","التعرف على كيفية تنظيم البيانات وعرضها في تقارير ولوحات معلومات بشكل مبسط."],"en":["Learn the basics of data analysis using Excel and Power BI.","Learn how to organize and present data in reports and dashboards simply."]},"benefits":{"ar":["لا يوجد."],"en":["None."]}}'::jsonb,
    '{"show_presenters":false,"show_goals":false,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}'::jsonb,
    '/assets/power bi.png', 'شهادة حضور', 'Attendance certificate', true, 'sdcommunity.sa@gmail.com', '2025-09-20T00:00:00+03:00'
  ) on conflict (legacy_id) do nothing;

insert into public.events (
    legacy_id, slug, committee_id, type, status, title_ar, title_en, schedule_type, start_date, end_date,
    location_mode, location_ar, location_en, goals, faq, details, display_config, cover_image_path,
    awards_ar, awards_en, certificate_available, contact_email, published_at
  ) values (
    4, 'cybersecurity-fundamentals-camp', (select id from public.committees where slug = 'tech-development'), 'bootcamp', 'published',
    'معسكر أساسيات الأمن السيبراني', 'Cybersecurity Fundamentals Camp', 'consecutive_range', '2024-09-15', '2024-09-19',
    'online', 'أونلاين', 'Online', '{"ar":[],"en":[]}'::jsonb, '[{"q_ar":"","q_en":"","a_ar":"تتوفر شهادة حضور بعد حضور المعسكر.","a_en":"An attendance certificate is available after attending the camp."},{"q_ar":"","q_en":"","a_ar":"في حال القبول، سيتم إرسال رسالة القبول عبر البريد الإلكتروني.","a_en":"If accepted, an approval email will be sent to your email."}]'::jsonb, '{"target_audience":{"ar":["طلاب، خريجون، موظفون"],"en":["Students, graduates, employees"]},"requirements":{"ar":["لا يوجد."],"en":["None."]},"responsibilities":{"ar":["الحضور والالتزام بوقت المعسكر.","المشاركة الفعالة أثناء الشرح والتطبيق.","متابعة الأنشطة والاستفادة من المحتوى المقدم."],"en":["Attend and respect the camp schedule.","Participate actively during lectures and practical activities.","Follow the activities and benefit from the provided content."]},"deliverables":{"ar":["التعرف على المفاهيم الأساسية في الأمن السيبراني.","اكتساب معرفة مبسطة بأهم الممارسات والأساليب المستخدمة لحماية الأنظمة والبيانات."],"en":["Understand the basic concepts of cybersecurity.","Gain practical knowledge of common practices and methods used to protect systems and data."]},"benefits":{"ar":["لا يوجد."],"en":["None."]}}'::jsonb,
    '{"show_presenters":false,"show_goals":false,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}'::jsonb,
    '/assets/Cyber.png', 'شهادة حضور', 'Attendance certificate', true, 'sdcommunity.sa@gmail.com', '2024-09-15T00:00:00+03:00'
  ) on conflict (legacy_id) do nothing;

insert into public.events (
    legacy_id, slug, committee_id, type, status, title_ar, title_en, schedule_type, start_date, end_date,
    location_mode, location_ar, location_en, goals, faq, details, display_config, cover_image_path,
    awards_ar, awards_en, certificate_available, contact_email, published_at
  ) values (
    5, 'ctf-fundamentals-camp', (select id from public.committees where slug = 'tech-development'), 'bootcamp', 'published',
    'معسكر أساسيات حل التقاط العلم CTF', 'CTF Fundamentals Camp', 'consecutive_range', '2024-10-27', '2024-11-01',
    'online', 'أونلاين', 'Online', '{"ar":[],"en":[]}'::jsonb, '[{"q_ar":"","q_en":"","a_ar":"تتوفر شهادة حضور بعد حضور المعسكر.","a_en":"An attendance certificate is available after attending the camp."},{"q_ar":"","q_en":"","a_ar":"في حال القبول، سيتم إرسال رسالة القبول عبر البريد الإلكتروني.","a_en":"If accepted, an approval email will be sent to your email."}]'::jsonb, '{"target_audience":{"ar":["طلاب، خريجون، موظفون"],"en":["Students, graduates, employees"]},"requirements":{"ar":["لا يوجد."],"en":["None."]},"responsibilities":{"ar":["الحضور والالتزام بوقت المعسكر.","المشاركة الفعالة أثناء التمارين والتحديات.","متابعة الشرح وتجربة المهارات المقدمة خلال المعسكر."],"en":["Attend and respect the camp schedule.","Participate actively in exercises and challenges.","Follow the explanation and practice the skills introduced."]},"deliverables":{"ar":["التعرف على أساسيات تحديات CTF وطريقة التعامل معها.","اكتساب معرفة مبسطة بأساليب تحليل وحل التحديات التقنية."],"en":["Learn the basics of CTF challenges and how to approach them.","Gain practical knowledge of analyzing and solving technical challenges."]},"benefits":{"ar":["لا يوجد."],"en":["None."]}}'::jsonb,
    '{"show_presenters":false,"show_goals":false,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}'::jsonb,
    '/assets/CTF.png', 'شهادة حضور', 'Attendance certificate', true, 'sdcommunity.sa@gmail.com', '2024-10-27T00:00:00+03:00'
  ) on conflict (legacy_id) do nothing;

insert into public.events (
    legacy_id, slug, committee_id, type, status, title_ar, title_en, schedule_type, start_date, end_date,
    location_mode, location_ar, location_en, goals, faq, details, display_config, cover_image_path,
    awards_ar, awards_en, certificate_available, contact_email, published_at
  ) values (
    6, 'huawei-startapps-camp', (select id from public.committees where slug = 'tech-development'), 'bootcamp', 'published',
    'معسكر نادي هواوي في ريادة الأعمال وصنع التطبيقات – StartApps', 'Huawei StartApps Entrepreneurship and App Development Camp', 'single_day', '2023-03-02', null,
    'online', 'أونلاين', 'Online', '{"ar":[],"en":[]}'::jsonb, '[{"q_ar":"","q_en":"","a_ar":"تتوفر شهادة حضور بعد حضور المعسكر.","a_en":"An attendance certificate is available after attending the camp."},{"q_ar":"","q_en":"","a_ar":"في حال القبول، سيتم إرسال رسالة القبول عبر البريد الإلكتروني.","a_en":"If accepted, an approval email will be sent to your email."}]'::jsonb, '{"target_audience":{"ar":["طلاب، خريجون، موظفون"],"en":["Students, graduates, employees"]},"requirements":{"ar":["لا يوجد."],"en":["None."]},"responsibilities":{"ar":["الحضور والالتزام بوقت المعسكر.","المشاركة الفعالة أثناء الأنشطة والتطبيقات.","متابعة المحتوى والاستفادة من المهارات المقدمة."],"en":["Attend and respect the camp schedule.","Participate actively in activities and practical exercises.","Follow the content and apply the skills introduced."]},"deliverables":{"ar":["التعرف على أساسيات ريادة الأعمال وتطوير الأفكار.","التعرف على المراحل الأساسية لتحويل الفكرة إلى تطبيق أو مشروع بشكل مبسط."],"en":["Learn the basics of entrepreneurship and idea development.","Understand the main stages of transforming an idea into an app or project in a simple way."]},"benefits":{"ar":["لا يوجد."],"en":["None."]}}'::jsonb,
    '{"show_presenters":false,"show_goals":false,"show_faq":true,"show_seats_remaining":false,"auto_close_registration":true,"show_details":true}'::jsonb,
    '/assets/Huwawi.png', 'شهادة حضور', 'Attendance certificate', true, 'sdcommunity.sa@gmail.com', '2023-03-02T00:00:00+03:00'
  ) on conflict (legacy_id) do nothing;

insert into public.event_private_details (event_id)
select id from public.events where legacy_id is not null
on conflict (event_id) do nothing;
