-- Sprint 09 · ART-003 — the six existing articles as rows (idempotent, keyed by legacy_id).
-- GENERATED by scripts/gen-legacy-articles.mjs from the old hardcoded detail page. Reading time is recomputed by
-- the table trigger, so the typed "3 min" values are gone. Authors: committee byline or guest names; tags paired
-- by position from the old Arabic/English lists.

-- tags
insert into public.tags (slug, label_ar, label_en) values ($sdc$ai$sdc$, $sdc$ذكاء اصطناعي$sdc$, $sdc$AI$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$prompt-engineering$sdc$, $sdc$هندسة الأوامر$sdc$, $sdc$Prompt Engineering$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$llm$sdc$, $sdc$Prompt Engineering$sdc$, $sdc$LLM$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$python$sdc$, $sdc$Python$sdc$, $sdc$Python$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$learning$sdc$, $sdc$تعلم$sdc$, $sdc$Learning$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$systems$sdc$, $sdc$انظمة$sdc$, $sdc$Systems$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$technology$sdc$, $sdc$تقنية$sdc$, $sdc$Technology$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$language$sdc$, $sdc$Language$sdc$, $sdc$Language$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$nlp$sdc$, $sdc$NLP$sdc$, $sdc$NLP$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$natural-language$sdc$, $sdc$لغة طبيعية$sdc$, $sdc$Natural Language$sdc$) on conflict (slug) do nothing;
insert into public.tags (slug, label_ar, label_en) values ($sdc$ethics$sdc$, $sdc$أخلاقيات$sdc$, $sdc$Ethics$sdc$) on conflict (slug) do nothing;

-- legacy article 1: Prompt Engineering
insert into public.articles (legacy_id, slug, committee_id, status, title_ar, title_en, excerpt_ar, excerpt_en,
  body_ar, body_en, resource_url, resource_label_ar, resource_label_en, published_at, created_at)
select 1, $sdc$prompt-engineering$sdc$, (select id from public.committees where slug = 'ai'), 'published',
  $sdc$هندسة الأوامر (Prompt Engineering)$sdc$, $sdc$Prompt Engineering$sdc$, $sdc$هندسة الأوامر (Prompt Engineering) هي عملية تصميم وتحسين الأوامر التي يتم إدخالها إلى نماذج الذكاء الاصطناعي، بهدف توجيهها للحصول على نتائج أكثر دقة وملاءمة للسياق من خلال اختيار الكلمات وصياغة الطلب بطريقة مدروسة.$sdc$, $sdc$Prompt Engineering is the process of designing and improving prompts entered into AI models to guide them toward more accurate and context-appropriate results through careful wording and clear instructions.$sdc$,
  $sdc$هندسة الأوامر (Prompt Engineering) هي عملية تصميم وتحسين الأوامر التي يتم إدخالها إلى نماذج الذكاء الاصطناعي، بهدف توجيهها للحصول على نتائج أكثر دقة وملاءمة للسياق من خلال اختيار الكلمات وصياغة الطلب بطريقة مدروسة.

تُستخدم هندسة الأوامر في العديد من المجالات، منها معالجة اللغة الطبيعية مثل تلخيص النصوص والترجمة، وروبوتات المحادثة والمساعدات الذكية، وأنظمة التوصية، وتوليد المحتوى، وتحليل البيانات، وأنظمة الإجابة عن الأسئلة.

وتكمن أهميتها في تحسين التفاعل بين الإنسان والذكاء الاصطناعي، ومساعدة النماذج على فهم استفسارات المستخدم بشكل أدق، وتطوير حلول فعالة للمهام المتخصصة، بالإضافة إلى دورها في تحسين أداء نماذج اللغة من خلال تجربة المدخلات وتحليل النتائج.

ولكتابة أمر أكثر فاعلية يمكن الاهتمام بعدة عناصر، مثل تحديد المهمة بوضوح، وإضافة السياق والمعلومات اللازمة، وتقديم مثال عند الحاجة، وتحديد الدور أو الشخصية المطلوبة من النموذج، وتوضيح شكل المخرجات، وتحديد نبرة الكتابة المناسبة.

كلما كان الطلب أكثر وضوحًا وتفصيلًا، ساعد ذلك في الحصول على إجابة أكثر دقة وجودة.

وللتوسع في المجال، يوفر المجتمع ملفًا يضم مجموعة من المصادر التعليمية حول هندسة الأوامر، تشمل مقالات ومدونات ودورات تعليمية.$sdc$, $sdc$Prompt Engineering is the process of designing and improving prompts entered into AI models to guide them toward more accurate and context-appropriate results through careful wording and clear instructions.

It is used in many areas, including natural language processing tasks such as text summarization and translation, chatbots and intelligent assistants, recommendation systems, content generation, data analysis, and question-answering systems.

Prompt engineering improves human-AI interaction by helping models understand user requests more accurately. It can also support the development of effective solutions for specialized tasks and improve language model performance through experimentation and analysis of different inputs.

An effective prompt can include several elements, such as a clearly defined task, relevant context, examples when needed, a specified role or persona, the desired output format, and an appropriate writing tone.

In general, the clearer and more detailed the request is, the more accurate and useful the resulting response can be.

For further learning, the community provides a collection of educational resources about Prompt Engineering, including articles, blogs, and courses.$sdc$,
  $sdc$https://drive.google.com/file/d/1zBwwEHcTvdgtgIAybbD2TYTAPYbqsN00/view?usp=drivesdk$sdc$, $sdc$مصادر تعلم هندسة الأوامر$sdc$, $sdc$Prompt Engineering Learning Resources$sdc$,
  '2024-08-15 09:00:00+03'::timestamptz, '2024-08-15 09:00:00+03'::timestamptz
where not exists (select 1 from public.articles where legacy_id = 1);

insert into public.article_authors (article_id, position, committee_id, display_name_ar, display_name_en)
select a.id, 0, (select id from public.committees where slug = 'ai'), $sdc$لجنة الذكاء الاصطناعي$sdc$, $sdc$AI Committee$sdc$
from public.articles a where a.legacy_id = 1
on conflict (article_id, position) do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 0 from public.articles a, public.tags t where a.legacy_id = 1 and t.slug = $sdc$ai$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 1 from public.articles a, public.tags t where a.legacy_id = 1 and t.slug = $sdc$prompt-engineering$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 2 from public.articles a, public.tags t where a.legacy_id = 1 and t.slug = $sdc$llm$sdc$
on conflict do nothing;

-- legacy article 2: Voice2Face Technology
insert into public.articles (legacy_id, slug, committee_id, status, title_ar, title_en, excerpt_ar, excerpt_en,
  body_ar, body_en, resource_url, resource_label_ar, resource_label_en, published_at, created_at)
select 2, $sdc$voice2face$sdc$, (select id from public.committees where slug = 'ai'), 'published',
  $sdc$تقنية Voice2Face$sdc$, $sdc$Voice2Face Technology$sdc$, $sdc$تقنية Voice2Face هي إحدى تقنيات الذكاء الاصطناعي التوليدي التي تهدف إلى إنشاء صورة تقريبية لملامح الوجه بالاعتماد على الصوت فقط.$sdc$, $sdc$Voice2Face is a generative AI technology that aims to create an approximate facial representation using only a person's voice.$sdc$,
  $sdc$تقنية Voice2Face هي إحدى تقنيات الذكاء الاصطناعي التوليدي التي تهدف إلى إنشاء صورة تقريبية لملامح الوجه بالاعتماد على الصوت فقط.

تعتمد التقنية على نماذج وشبكات عصبية عميقة يتم تدريبها باستخدام بيانات تربط بين صور الوجوه والمقاطع الصوتية، حتى تتعلم العلاقات بين خصائص الصوت وبعض السمات المرئية للوجه. وعند إدخال صوت جديد، يحاول النموذج إنشاء وجه تقريبي استنادًا إلى الأنماط التي تعلمها.

يمكن الاستفادة من هذه التقنية في عدة مجالات، مثل الأمن والتحقيقات الجنائية للمساعدة في تضييق نطاق الاحتمالات، وخدمة العملاء والتجارب الرقمية، والتفاعل الاجتماعي، وصناعة الألعاب، والإنتاج السينمائي والتلفزيوني.

كما ظهرت تجارب وتطبيقات تستخدم تقنيات مشابهة لتطوير الشخصيات الرقمية وجعل التفاعل معها أكثر تخصيصًا.

لكن Voice2Face تفتح أيضًا بابًا لتحديات مهمة، أبرزها الخصوصية والتزييف العميق والثقة بالمحتوى الرقمي. فقد تسهم تقنيات توليد الوجوه والأصوات في جعل التمييز بين المحتوى الحقيقي والمصطنع أكثر صعوبة.

لذلك تقدم Voice2Face مثالًا مثيرًا على تطور الذكاء الاصطناعي وقدرته على اكتشاف العلاقات بين الصوت والصورة، مع أهمية الانتباه إلى الاستخدام المسؤول والجوانب المتعلقة بالخصوصية والثقة الرقمية.$sdc$, $sdc$Voice2Face is a generative AI technology that aims to create an approximate facial representation using only a person's voice.

The technology relies on deep neural networks trained on data that pairs facial images with voice recordings. Through this training, the model learns relationships between vocal characteristics and certain visual facial features. When a new voice is provided, it attempts to generate an approximate face based on the patterns it has learned.

Potential applications include security and criminal investigations, customer service and digital experiences, social interaction, gaming, and film and television production.

Similar technologies have also been explored for developing digital characters and creating more personalized interactive experiences.

However, Voice2Face also raises important challenges related to privacy, deepfakes, and trust in digital content. Technologies capable of generating faces and voices can make distinguishing authentic content from synthetic content more difficult.

Voice2Face therefore provides an interesting example of how AI can discover relationships between audio and visual information, while highlighting the importance of responsible use, privacy, and digital trust.$sdc$,
  null, null, null,
  '2024-11-25 09:00:00+03'::timestamptz, '2024-11-25 09:00:00+03'::timestamptz
where not exists (select 1 from public.articles where legacy_id = 2);

insert into public.article_authors (article_id, position, display_name_ar, display_name_en)
select a.id, 0, $sdc$الين الزهراني$sdc$, $sdc$Alin Al-Zahrani$sdc$ from public.articles a where a.legacy_id = 2
on conflict (article_id, position) do nothing;

insert into public.article_authors (article_id, position, display_name_ar, display_name_en)
select a.id, 1, $sdc$مريم النعيم$sdc$, $sdc$Maryam Al-Neaim$sdc$ from public.articles a where a.legacy_id = 2
on conflict (article_id, position) do nothing;

insert into public.article_authors (article_id, position, display_name_ar, display_name_en)
select a.id, 2, $sdc$غلا العتيبي$sdc$, $sdc$Ghala Alotibi$sdc$ from public.articles a where a.legacy_id = 2
on conflict (article_id, position) do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 0 from public.articles a, public.tags t where a.legacy_id = 2 and t.slug = $sdc$ai$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 1 from public.articles a, public.tags t where a.legacy_id = 2 and t.slug = $sdc$python$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 2 from public.articles a, public.tags t where a.legacy_id = 2 and t.slug = $sdc$learning$sdc$
on conflict do nothing;

-- legacy article 3: Recommendation Systems
insert into public.articles (legacy_id, slug, committee_id, status, title_ar, title_en, excerpt_ar, excerpt_en,
  body_ar, body_en, resource_url, resource_label_ar, resource_label_en, published_at, created_at)
select 3, $sdc$recommendation-systems$sdc$, (select id from public.committees where slug = 'ai'), 'published',
  $sdc$أنظمة التوصية (Recommendation Systems)$sdc$, $sdc$Recommendation Systems$sdc$, $sdc$أنظمة التوصية (Recommendation Systems) هي أنظمة تعتمد على الذكاء الاصطناعي وتعلم الآلة وتحليل البيانات بهدف تصفية المحتوى الرقمي وتخصيصه لكل مستخدم.$sdc$, $sdc$Recommendation Systems use artificial intelligence, machine learning, and data analysis to filter and personalize digital content for each user.$sdc$,
  $sdc$أنظمة التوصية (Recommendation Systems) هي أنظمة تعتمد على الذكاء الاصطناعي وتعلم الآلة وتحليل البيانات بهدف تصفية المحتوى الرقمي وتخصيصه لكل مستخدم.

تعتمد هذه الأنظمة على تحليل السلوك الرقمي، مثل عمليات البحث والمشاهدة والمشتريات والتفاعل مع المحتوى، ثم تربط هذه البيانات بالاهتمامات والأنماط لتوقع ما قد يفضله المستخدم لاحقًا.

وتستخدم أنظمة التوصية نوعين رئيسيين من البيانات: البيانات الصريحة (Explicit Data)، مثل التقييمات والتعليقات والإعجاب وعدم الإعجاب، والبيانات الضمنية (Implicit Data)، مثل سجل البحث والنقرات ومدة المشاهدة وإضافة المنتجات إلى السلة والمشتريات السابقة.

ومن أشهر طرق عملها التصفية التعاونية (Collaborative Filtering)، التي تعتمد على سلوك المستخدم وسلوك مستخدمين آخرين لديهم اهتمامات متشابهة، فتقترح محتوى أو منتجات بناءً على هذه الأنماط المشتركة.

كما توجد التصفية المعتمدة على المحتوى (Content-Based Filtering)، التي تعتمد على خصائص المحتوى الذي أعجب المستخدم سابقًا، والتصفية المعتمدة على السياق (Context-Based Filtering)، التي تأخذ في الاعتبار عوامل مثل الوقت والموقع وظروف الاستخدام.

ومن الأمثلة على ذلك المتاجر الإلكترونية مثل Amazon، حيث يمكن أن تظهر للمستخدم منتجات مشابهة لما شاهده أو اشتراه، ومنتجات تكمل مشترياته، واقتراحات مبنية على سلوك مستخدمين مشابهين.

هذه الأنظمة تجعل الوصول إلى الخيارات المناسبة أسهل وسط الكم الكبير من المحتوى والمنتجات، وتحوّل تجربة المستخدم العامة إلى تجربة أكثر تخصيصًا.

ومع ذلك، من المهم معرفة أن الأجهزة لا "تقرأ أفكارنا"، بل تقوم الأنظمة بتحليل الإشارات الناتجة عن سلوكنا الرقمي وتحويلها إلى أنماط تساعدها في تحديد ما قد يهمنا، ويبقى القرار النهائي للمستخدم.$sdc$, $sdc$Recommendation Systems use artificial intelligence, machine learning, and data analysis to filter and personalize digital content for each user.

These systems analyze digital behavior such as searches, views, purchases, and interactions, then connect these signals to patterns and interests in order to predict what the user may prefer next.

Recommendation systems use two main types of data. Explicit Data includes ratings, comments, likes, and dislikes, while Implicit Data includes search history, clicks, viewing duration, items added to a cart, and previous purchases.

One common method is Collaborative Filtering, which uses the behavior of a user and other users with similar interests to recommend content or products based on shared patterns.

Content-Based Filtering recommends items according to characteristics of content the user previously liked, while Context-Based Filtering considers factors such as time, location, and usage context.

Online stores such as Amazon provide a familiar example, where users may receive recommendations for similar products, complementary purchases, or suggestions based on the behavior of similar users.

These systems make it easier to navigate large amounts of content and products while creating a more personalized user experience.

However, these systems do not literally read our thoughts. They analyze signals produced by our digital behavior and transform them into patterns that help predict what may interest us, while the final choice remains with the user.$sdc$,
  null, null, null,
  '2025-09-12 09:00:00+03'::timestamptz, '2025-09-12 09:00:00+03'::timestamptz
where not exists (select 1 from public.articles where legacy_id = 3);

insert into public.article_authors (article_id, position, committee_id, display_name_ar, display_name_en)
select a.id, 0, (select id from public.committees where slug = 'ai'), $sdc$لجنة الذكاء الاصطناعي$sdc$, $sdc$AI Committee$sdc$
from public.articles a where a.legacy_id = 3
on conflict (article_id, position) do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 0 from public.articles a, public.tags t where a.legacy_id = 3 and t.slug = $sdc$systems$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 1 from public.articles a, public.tags t where a.legacy_id = 3 and t.slug = $sdc$learning$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 2 from public.articles a, public.tags t where a.legacy_id = 3 and t.slug = $sdc$ai$sdc$
on conflict do nothing;

-- legacy article 4: Chinese and English Applications
insert into public.articles (legacy_id, slug, committee_id, status, title_ar, title_en, excerpt_ar, excerpt_en,
  body_ar, body_en, resource_url, resource_label_ar, resource_label_en, published_at, created_at)
select 4, $sdc$chinese-and-english-applications$sdc$, (select id from public.committees where slug = 'ai'), 'published',
  $sdc$التطبيقات الصينية والإنجليزية$sdc$, $sdc$Chinese and English Applications$sdc$, $sdc$تختلف واجهات التطبيقات الصينية والإنجليزية في العديد من التفاصيل، ويعود جزء كبير من هذه الاختلافات إلى الثقافة وعادات المستخدمين وتوقعاتهم من تجربة التطبيق.$sdc$, $sdc$Chinese and English-language applications can differ in many interface details, with much of this variation influenced by culture, user habits, and expectations.$sdc$,
  $sdc$تختلف واجهات التطبيقات الصينية والإنجليزية في العديد من التفاصيل، ويعود جزء كبير من هذه الاختلافات إلى الثقافة وعادات المستخدمين وتوقعاتهم من تجربة التطبيق.

من أبرز الاختلافات المساحات البيضاء؛ إذ قد تبدو بعض التطبيقات الصينية مزدحمة للمستخدم الغربي بسبب اختلاف استخدام المساحات وأحجام النصوص وارتفاع الأسطر. وفي المقابل، تميل هذه التطبيقات إلى وضع قدر أكبر من الوظائف والنصوص والمعلومات والصور في المساحة نفسها.

وتنتشر النوافذ المنبثقة الترويجية في بعض التطبيقات الصينية بشكل أكبر. ويمكن تشبيه ذلك بأجواء الأسواق الصينية المزدحمة التي يحاول فيها البائعون جذب انتباه الزوار، وهي تجربة قد تبدو مزعجة لبعض المستخدمين من ثقافات أخرى لكنها مألوفة لدى مستخدمين آخرين.

وتختلف أيضًا أيقونات التطبيقات؛ إذ تستخدم بعض التطبيقات الصينية الأحرف الصينية والعناصر البصرية داخل الأيقونة، وقد تتغير الأيقونة بحسب المواسم والمناسبات لجذب انتباه المستخدم، كما ظهر في بعض التطبيقات خلال أحداث ومناسبات مختلفة.

أما شاشات بداية التطبيق، فقد تستخدم بعض التطبيقات الصينية الإعلانات أو المحتوى الترويجي بدلًا من الاكتفاء بعرض شعار التطبيق.

كما تميل بعض التصاميم الصينية إلى استخدام ألوان متعددة ودافئة وعناصر بصرية كثيرة لجذب الانتباه.

وتظهر الحيوانات كذلك كرموز تحمل معاني ثقافية؛ فبعض الحيوانات لها دلالات خاصة في الثقافة الصينية، مثل ارتباط بعض الرموز بطول العمر أو الثراء، ويمكن الاستفادة منها في تصميم هوية التطبيق.

هذه الاختلافات توضح أن تصميم واجهات وتجربة المستخدم لا يعتمد على الجانب الجمالي فقط، بل يتأثر أيضًا بثقافة المستخدم وعاداته وتوقعاته.$sdc$, $sdc$Chinese and English-language applications can differ in many interface details, with much of this variation influenced by culture, user habits, and expectations.

One noticeable difference is the use of white space. Some Chinese applications may appear visually dense to Western users because of different approaches to spacing, text size, and line height. They may also place more functionality, text, information, and images within the same screen space.

Promotional pop-ups are also common in some Chinese applications. This can be compared to the busy atmosphere of physical markets where sellers actively compete for attention. While this may feel distracting to users from other cultures, it can be more familiar to local users.

Application icons can also differ. Some Chinese apps use Chinese characters and additional visual elements, and icons may change according to seasons or major events to attract attention.

Some Chinese applications may display advertising or promotional material on their launch screens rather than showing only the application logo.

Their interfaces may also use multiple warm and vivid colors to draw attention.

Animals can appear as culturally meaningful symbols as well. Certain animals carry specific meanings in Chinese culture, such as associations with longevity or wealth, which can influence branding and interface design.

These differences demonstrate that UI and UX design are shaped not only by visual aesthetics but also by culture, habits, and user expectations.$sdc$,
  null, null, null,
  '2023-06-11 09:00:00+03'::timestamptz, '2023-06-11 09:00:00+03'::timestamptz
where not exists (select 1 from public.articles where legacy_id = 4);

insert into public.article_authors (article_id, position, committee_id, display_name_ar, display_name_en)
select a.id, 0, (select id from public.committees where slug = 'ai'), $sdc$لجنة الذكاء الاصطناعي$sdc$, $sdc$AI Committee$sdc$
from public.articles a where a.legacy_id = 4
on conflict (article_id, position) do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 0 from public.articles a, public.tags t where a.legacy_id = 4 and t.slug = $sdc$technology$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 1 from public.articles a, public.tags t where a.legacy_id = 4 and t.slug = $sdc$language$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 2 from public.articles a, public.tags t where a.legacy_id = 4 and t.slug = $sdc$learning$sdc$
on conflict do nothing;

-- legacy article 5: AI in Games and Reinforcement Learning
insert into public.articles (legacy_id, slug, committee_id, status, title_ar, title_en, excerpt_ar, excerpt_en,
  body_ar, body_en, resource_url, resource_label_ar, resource_label_en, published_at, created_at)
select 5, $sdc$ai-in-games-and-reinforcement-learning$sdc$, (select id from public.committees where slug = 'ai'), 'published',
  $sdc$الذكاء الاصطناعي في الألعاب والتعلّم المعزّز$sdc$, $sdc$AI in Games and Reinforcement Learning$sdc$, $sdc$كيف يستطيع الذكاء الاصطناعي التفوق في الألعاب واتخاذ قرارات ذكية؟ إحدى التقنيات الأساسية وراء ذلك هي التعلم المعزز (Reinforcement Learning).$sdc$, $sdc$How can artificial intelligence become highly capable at games and make intelligent decisions? One of the key techniques behind this is Reinforcement Learning.$sdc$,
  $sdc$كيف يستطيع الذكاء الاصطناعي التفوق في الألعاب واتخاذ قرارات ذكية؟ إحدى التقنيات الأساسية وراء ذلك هي التعلم المعزز (Reinforcement Learning).

في هذا النوع من التعلم يوجد وكيل ذكي (Agent) يتفاعل مع بيئة معينة (Environment). يراقب الوكيل الحالة (State)، ثم يختار فعلًا معينًا (Action)، ويحصل بعد ذلك على مكافأة أو عقوبة (Reward) بناءً على نتيجة قراره.

الوكيل الذكي هو الكيان الذي يتخذ القرارات والأفعال داخل اللعبة. ومع تكرار التجارب يتعلم تحسين استراتيجيته واختيار القرارات التي تحقق نتائج أفضل.

أما البيئة (Environment) فهي كل ما يحيط بالوكيل، مثل قواعد اللعبة ومواقع الأشياء وتصرفات الخصوم والتحديات والنتائج المترتبة على أفعاله. ومع كل خطوة تتغير استجابة البيئة للفعل وتمنح الوكيل مكافأة أو تغذية راجعة تساعده على التعلم.

تبدأ عملية التعلم عندما يجرب الوكيل حركة، ثم تعطيه البيئة نتيجة قد تكون نجاحًا أو فشلًا، وبعدها يحصل على مكافأة أو عقوبة. ومع تكرار آلاف المحاولات يتعلم الأفعال التي تمنحه مكافآت أكبر ويبني استراتيجية أفضل للوصول إلى الفوز.

ومن التقنيات المتقدمة التعلم المعزز العميق (Deep Reinforcement Learning)، الذي يجمع بين التعلم المعزز وتقنيات التعلم العميق للتعامل مع مواقف أكثر تعقيدًا.

ولا يقتصر استخدام التعلم المعزز على الألعاب، بل توجد له تطبيقات في السيارات ذاتية القيادة لتعلم الطرق، وأنظمة التنبؤ والتحكم في الاقتصاد والطاقة، والروبوتات التي تتعلم الحركة.

ويستطيع الذكاء الاصطناعي التفوق في بعض الألعاب لأنه قادر على خوض عدد هائل من التجارب بسرعة، وتذكر الاستراتيجيات والنتائج، والاستمرار في التعلم والتكرار دون توقف، مما يمنحه قدرة كبيرة على تحسين أدائه.$sdc$, $sdc$How can artificial intelligence become highly capable at games and make intelligent decisions? One of the key techniques behind this is Reinforcement Learning.

In reinforcement learning, an intelligent Agent interacts with an Environment. The agent observes the current State, chooses an Action, and then receives a Reward or penalty based on the outcome of its decision.

The agent is the entity responsible for making decisions and performing actions inside the game. Through repeated experiences, it learns to improve its strategy and select actions that produce better results.

The Environment includes everything surrounding the agent, such as game rules, object locations, opponents, challenges, and the consequences of its actions. After each action, the environment responds and provides a reward or feedback that helps the agent learn.

The learning process begins when the agent attempts an action. The environment then produces an outcome, such as success or failure, followed by a reward or penalty. After thousands of attempts, the agent learns which actions produce higher rewards and develops a stronger strategy.

Deep Reinforcement Learning combines reinforcement learning with deep learning techniques to handle more complex situations.

Its applications extend beyond games to self-driving cars learning road navigation, prediction and control systems in economics and energy, and robots learning how to move.

AI can become extremely capable in some games because it can perform huge numbers of experiments quickly, remember strategies and outcomes, and continuously learn through repetition.$sdc$,
  null, null, null,
  '2025-10-17 09:00:00+03'::timestamptz, '2025-10-17 09:00:00+03'::timestamptz
where not exists (select 1 from public.articles where legacy_id = 5);

insert into public.article_authors (article_id, position, committee_id, display_name_ar, display_name_en)
select a.id, 0, (select id from public.committees where slug = 'ai'), $sdc$لجنة الذكاء الاصطناعي$sdc$, $sdc$AI Committee$sdc$
from public.articles a where a.legacy_id = 5
on conflict (article_id, position) do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 0 from public.articles a, public.tags t where a.legacy_id = 5 and t.slug = $sdc$ai$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 1 from public.articles a, public.tags t where a.legacy_id = 5 and t.slug = $sdc$nlp$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 2 from public.articles a, public.tags t where a.legacy_id = 5 and t.slug = $sdc$natural-language$sdc$
on conflict do nothing;

-- legacy article 6: AI Applications in Sentiment Analysis
insert into public.articles (legacy_id, slug, committee_id, status, title_ar, title_en, excerpt_ar, excerpt_en,
  body_ar, body_en, resource_url, resource_label_ar, resource_label_en, published_at, created_at)
select 6, $sdc$ai-sentiment-analysis$sdc$, (select id from public.committees where slug = 'ai'), 'published',
  $sdc$تطبيقات الذكاء الاصطناعي في تحليل المشاعر$sdc$, $sdc$AI Applications in Sentiment Analysis$sdc$, $sdc$أصبح الذكاء الاصطناعي جزءًا من حياتنا اليومية، ومن المجالات التي تتطور باستمرار قدرته على تحليل المشاعر البشرية والتفاعل معها بصورة أكثر ملاءمة.$sdc$, $sdc$Artificial intelligence has become part of everyday life, and one continuously developing area is its ability to analyze indicators associated with human emotions and respond more appropriately.$sdc$,
  $sdc$أصبح الذكاء الاصطناعي جزءًا من حياتنا اليومية، ومن المجالات التي تتطور باستمرار قدرته على تحليل المشاعر البشرية والتفاعل معها بصورة أكثر ملاءمة.

تحليل المشاعر هو قدرة الأنظمة على التعرف على مؤشرات مرتبطة بالمشاعر البشرية باستخدام تقنيات مختلفة، مثل تحليل النصوص والتعرف على تعبيرات الوجه وتحليل نبرة الصوت، بهدف تحسين التفاعل وفهم المستخدم بصورة أفضل.

في تحليل النصوص، تُستخدم تقنيات تحليل المشاعر لفهم الكلمات والجمل المكتوبة والتعرف على المشاعر أو الانطباعات التي تعكسها.

أما التعرف على تعبيرات الوجه، فيعتمد على الكاميرات وتقنيات الرؤية الحاسوبية لتحليل تعبيرات قد ترتبط بمشاعر مثل السعادة أو الغضب أو الحزن.

وفي تحليل الصوت، يمكن للذكاء الاصطناعي تحليل نبرة الصوت واستخدامها كمؤشر يساعد في تقدير الحالة العاطفية للمتحدث.

وتوجد لهذه التقنيات تطبيقات في مجالات متعددة. ففي الرعاية الصحية يمكن استخدام الأجهزة الذكية لمتابعة مؤشرات مثل التوتر والقلق، كما يمكن لروبوتات المحادثة تحليل اللغة المكتوبة أو الصوتية وتقديم تفاعل داعم، لتكون أداة مساندة للمتخصصين.

وفي التسويق يمكن للشركات تحليل مشاعر المستخدمين وتفاعلهم مع المنتجات، والاستفادة من النتائج في فهم الجمهور ودعم الحملات التسويقية وتحسين الخدمات بما يناسب احتياجات العملاء.

وفي التعليم يمكن للأنظمة الذكية تحليل مؤشرات مثل تعبيرات الوجه وحركات العين والتفاعل أثناء التعلم، بما يساعد المعلمين على فهم احتياجات الطلاب بصورة أفضل وتقديم الدعم المناسب وتحسين تجربة التعليم وفق الفروقات الفردية.

أما وسائل التواصل الاجتماعي، فتحتوي على عدد ضخم من الإعجابات والتعليقات والصور ومقاطع الفيديو. ويمكن للذكاء الاصطناعي تحليل هذه التفاعلات واستخلاص مؤشرات عن انطباعات الجمهور، مما يساعد في معرفة المحتوى الذي يفضله المستخدمون وفهم الانطباع العام.

ورغم أن هذا المجال لا يزال في مراحل تطور مستمرة، فإن تطبيقاته تظهر إمكانات واعدة في العديد من المجالات. ويبقى السؤال: إلى أي مدى يمكن للآلة أن تفهم مشاعر الإنسان فعلًا؟$sdc$, $sdc$Artificial intelligence has become part of everyday life, and one continuously developing area is its ability to analyze indicators associated with human emotions and respond more appropriately.

Sentiment and emotion analysis refers to the ability of systems to identify emotional indicators using techniques such as text analysis, facial-expression recognition, and voice-tone analysis in order to improve interaction and better understand users.

In text analysis, sentiment-analysis techniques examine written words and sentences to identify the emotions or impressions they may express.

Facial-expression recognition uses cameras and computer-vision technologies to analyze expressions that may be associated with emotions such as happiness, anger, or sadness.

Voice analysis can examine tone and use it as one indicator for estimating the emotional state of a speaker.

These technologies have applications across several fields. In healthcare, smart devices can help monitor indicators such as stress and anxiety, while chatbots can analyze written or spoken language and provide supportive interactions as tools that assist professionals.

In marketing, companies can analyze customer reactions and interactions with products, using the results to better understand audiences, support marketing campaigns, and improve services.

In education, intelligent systems can analyze signals such as facial expressions, eye movements, and engagement during learning. This may help teachers better understand individual student needs and provide more appropriate support.

Social media contains enormous amounts of likes, comments, images, and videos. AI can analyze these interactions to identify patterns in audience sentiment, understand which content users prefer, and estimate general reactions.

Although this field is still developing, its applications show promising possibilities across many areas. The broader question remains: to what extent can a machine truly understand human emotions?$sdc$,
  null, null, null,
  '2025-09-26 09:00:00+03'::timestamptz, '2025-09-26 09:00:00+03'::timestamptz
where not exists (select 1 from public.articles where legacy_id = 6);

insert into public.article_authors (article_id, position, committee_id, display_name_ar, display_name_en)
select a.id, 0, (select id from public.committees where slug = 'ai'), $sdc$لجنة الذكاء الاصطناعي$sdc$, $sdc$AI Committee$sdc$
from public.articles a where a.legacy_id = 6
on conflict (article_id, position) do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 0 from public.articles a, public.tags t where a.legacy_id = 6 and t.slug = $sdc$ai$sdc$
on conflict do nothing;

insert into public.article_tags (article_id, tag_id, position)
select a.id, t.id, 1 from public.articles a, public.tags t where a.legacy_id = 6 and t.slug = $sdc$ethics$sdc$
on conflict do nothing;
