/** Home page strings (message keys `home.*` of the spec). Owner copy that is still pending is not in here. */
export const HOME_COPY = {
  ar: {
    announcement: 'التسجيل مفتوح',
    heroTitle: 'المجتمع السعودي للمطورين',
    heroLede: 'نبني مجتمعاً سعودياً يقود المستقبل بالذكاء الاصطناعي والتقنيات الحديثة.',
    join: 'انضم إلى المجتمع',
    apply: 'قدّم طلب العضوية',
    browse: 'تصفّح الفعاليات',
    statsLabel: 'المجتمع بالأرقام',
    stats: {
      members: 'عضواً في الدليل',
      events: 'فعالية أُقيمت',
      committees: 'لجان نشطة',
      certificates: 'شهادة صدرت',
    },
    eventsTitle: 'الفعاليات القادمة',
    eventsLede: 'ورش ولقاءات مفتوحة، حضورياً وعن بُعد.',
    pastTitle: 'فعاليات سابقة',
    pastLede: 'نظرة على ما أنجزناه معاً.',
    eventsAll: 'عرض كل الفعاليات',
    articlesTitle: 'أحدث المقالات',
    articlesLede: 'ما يكتبه أعضاء المجتمع عن التقنية.',
    articlesAll: 'كل المقالات',
    partnersTitle: 'شركاؤنا',
    ctaTitle: 'انضم إلى المجتمع',
    ctaOpen: (date: string) => `باب العضوية مفتوح حتى ${date}`,
    ctaScheduled: (date: string) => `يفتح باب العضوية في ${date}`,
    ctaClosed: 'تابعنا لتعرف موعد الدورة القادمة',
    whyTitle: 'لماذا تنضم؟',
    whyLede: 'مجتمع يفتح لك الباب للتعلّم والمشاركة وبناء العلاقات المهنية.',
    whyMembers: 'للأعضاء',
    whyPartners: 'للشركاء',
    whyCtaTitle: 'ابدأ رحلتك مع المجتمع',
    whyCtaApply: 'قدّم طلب العضوية',
    why: {
      members: [
        ['BookOpen', 'ورش ولقاءات تقنية', 'فعاليات عملية يقدّمها مختصون في مجالات متنوعة.'],
        ['Users', 'شبكة من المطورين', 'تعرّف على أقرانك وزملاء المستقبل وشاركهم الخبرة.'],
        ['Award', 'شهادات حضور', 'تصلك شهادة موثّقة بعد كل فعالية تحضرها.'],
        ['Rocket', 'فرص للمشاركة', 'قدّم محتوى، وانضم إلى لجنة، وشارك في تنظيم الفعاليات.'],
      ],
      partners: [
        ['Handshake', 'الوصول إلى المواهب', 'تواصل مع مطورين وطلاب شغوفين بالتقنية.'],
        ['Megaphone', 'حضور في الفعاليات', 'اعرض مبادراتك أمام جمهور تقني مهتم.'],
        ['Lightbulb', 'ورش مشتركة', 'نظّم ورشاً ومسابقات مع لجان المجتمع.'],
        ['Building2', 'أثر مشترك', 'ساهم في بناء جيل سعودي من المطورين.'],
      ],
    },
    membersTitle: 'أعضاء المجتمع',
    membersLede: 'تعرّف على بعض من يصنعون المجتمع.',
    membersAll: 'كل الأعضاء',
    faqTitle: 'الأسئلة الشائعة',
    faq: [
      [
        'من يمكنه الانضمام إلى المجتمع؟',
        'الباب مفتوح للطلاب والخريجين والعاملين في التقنية من داخل المملكة. تُستقبل الطلبات خلال فترات التسجيل المعلنة.',
      ],
      [
        'هل حضور الفعاليات مجاني؟',
        'نعم، حضور فعاليات المجتمع مجاني ويتطلب التسجيل المسبق، وبعضها مخصص للأعضاء فقط.',
      ],
      [
        'هل أحتاج إلى حساب للتسجيل في فعالية؟',
        'لا. يمكنك التسجيل بالاسم والبريد ورقم الجوال دون إنشاء حساب.',
      ],
      [
        'كيف أحصل على شهادة الحضور؟',
        'تُرسل الشهادة إلى بريدك بعد اعتماد حضورك، ويمكن التحقق منها من صفحة التحقق.',
      ],
      ['كيف أتواصل مع المجتمع؟', 'عبر حسابات المجتمع في المنصات الاجتماعية المذكورة أسفل الصفحة.'],
    ],
    follow: 'تابعنا على',
    newTab: '(يفتح في نافذة جديدة)',
  },
  en: {
    announcement: 'Registration open',
    heroTitle: 'Saudi Developer Community',
    heroLede: 'We build a Saudi community that leads the future with AI and modern technologies.',
    join: 'Join the community',
    apply: 'Apply for membership',
    browse: 'Browse events',
    statsLabel: 'The community in numbers',
    stats: {
      members: 'listed members',
      events: 'events held',
      committees: 'active committees',
      certificates: 'certificates issued',
    },
    eventsTitle: 'Upcoming events',
    eventsLede: 'Open workshops and meetups, in person and online.',
    pastTitle: 'Past events',
    pastLede: 'A look at what we have done together.',
    eventsAll: 'View all events',
    articlesTitle: 'Latest articles',
    articlesLede: 'What community members write about technology.',
    articlesAll: 'All articles',
    partnersTitle: 'Our partners',
    ctaTitle: 'Join the community',
    ctaOpen: (date: string) => `Applications are open until ${date}`,
    ctaScheduled: (date: string) => `Applications open on ${date}`,
    ctaClosed: 'Follow us to hear when the next intake opens',
    whyTitle: 'Why join?',
    whyLede:
      'A community that opens the door to learning, taking part and building professional ties.',
    whyMembers: 'For members',
    whyPartners: 'For partners',
    whyCtaTitle: 'Start your journey with the community',
    whyCtaApply: 'Apply for membership',
    why: {
      members: [
        [
          'BookOpen',
          'Workshops and meetups',
          'Hands-on events led by specialists across many fields.',
        ],
        [
          'Users',
          'A network of developers',
          'Meet your peers and future colleagues and share experience.',
        ],
        [
          'Award',
          'Certificates of attendance',
          'Get a verifiable certificate after every event you attend.',
        ],
        [
          'Rocket',
          'Ways to take part',
          'Publish content, join a committee and help organise events.',
        ],
      ],
      partners: [
        [
          'Handshake',
          'Reach talent',
          'Connect with developers and students passionate about technology.',
        ],
        [
          'Megaphone',
          'Presence at events',
          'Present your initiatives to an engaged technical audience.',
        ],
        [
          'Lightbulb',
          'Joint workshops',
          'Run workshops and competitions with the community committees.',
        ],
        ['Building2', 'Shared impact', 'Help build a generation of Saudi developers.'],
      ],
    },
    membersTitle: 'Community members',
    membersLede: 'Meet some of the people who make the community.',
    membersAll: 'All members',
    faqTitle: 'Frequently asked questions',
    faq: [
      [
        'Who can join the community?',
        'Students, graduates and tech professionals in the Kingdom. Applications are taken during announced intake windows.',
      ],
      [
        'Is attending events free?',
        'Yes. Community events are free and need registration in advance; some are for members only.',
      ],
      [
        'Do I need an account to register for an event?',
        'No. You can register with your name, e-mail and mobile number, without creating an account.',
      ],
      [
        'How do I get a certificate of attendance?',
        'The certificate is e-mailed after your attendance is approved, and anyone can verify it on the verification page.',
      ],
      [
        'How do I contact the community?',
        'Through the community accounts on the social platforms listed in the footer.',
      ],
    ],
    follow: 'Follow us on',
    newTab: '(opens in a new tab)',
  },
} as const;
