/** Home page strings (message keys `home.*` of the spec). Owner copy that is still pending is not in here. */
export const HOME_COPY = {
  ar: {
    announcement: 'التسجيل مفتوح',
    heroTitle: 'المجتمع السعودي للمطورين',
    heroLede: 'نبني مجتمعاً سعودياً يقود المستقبل بالذكاء الاصطناعي والتقنيات الحديثة.',
    join: 'انضم إلى المجتمع',
    apply: 'قدّم طلب العضوية',
    browse: 'تصفّح الفعاليات',
    statsLabel: 'المجتمع بالأرقام',
    stats: {
      members: 'عضواً في الدليل',
      events: 'فعالية أُقيمت',
      committees: 'لجان نشطة',
      certificates: 'شهادة صدرت',
    },
    eventsTitle: 'الفعاليات القادمة',
    eventsLede: 'ورش ولقاءات مفتوحة، حضورياً وعن بُعد.',
    pastTitle: 'فعاليات سابقة',
    pastLede: 'نظرة على ما أنجزناه معاً.',
    eventsAll: 'عرض كل الفعاليات',
    articlesTitle: 'أحدث المقالات',
    articlesLede: 'ما يكتبه أعضاء المجتمع عن التقنية.',
    articlesAll: 'كل المقالات',
    partnersTitle: 'شركاؤنا',
    ctaTitle: 'انضم إلى المجتمع',
    ctaOpen: (date: string) => `باب العضوية مفتوح حتى ${date}`,
    ctaScheduled: (date: string) => `يفتح باب العضوية في ${date}`,
    ctaClosed: 'تابعنا لتعرف موعد الدورة القادمة',
    follow: 'تابعنا على',
    newTab: '(يفتح في نافذة جديدة)',
  },
  en: {
    announcement: 'Registration open',
    heroTitle: 'Saudi Developer Community',
    heroLede: 'We build a Saudi community that leads the future with AI and modern technologies.',
    join: 'Join the community',
    apply: 'Apply for membership',
    browse: 'Browse events',
    statsLabel: 'The community in numbers',
    stats: {
      members: 'listed members',
      events: 'events held',
      committees: 'active committees',
      certificates: 'certificates issued',
    },
    eventsTitle: 'Upcoming events',
    eventsLede: 'Open workshops and meetups, in person and online.',
    pastTitle: 'Past events',
    pastLede: 'A look at what we have done together.',
    eventsAll: 'View all events',
    articlesTitle: 'Latest articles',
    articlesLede: 'What community members write about technology.',
    articlesAll: 'All articles',
    partnersTitle: 'Our partners',
    ctaTitle: 'Join the community',
    ctaOpen: (date: string) => `Applications are open until ${date}`,
    ctaScheduled: (date: string) => `Applications open on ${date}`,
    ctaClosed: 'Follow us to hear when the next intake opens',
    follow: 'Follow us on',
    newTab: '(opens in a new tab)',
  },
} as const;
